### ISSUE TITLE
Double upload causing conda error

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/psdm_qs_cli#8]
CI is set up to upload to anaconda twice. In builds for dependent packages, conda is failing because its trying to compare the hash of the downloaded file with the hash of the other file.

Fix for this could probably be as simple as deleting or renaming one of them. It could also be investigated why there's a difference in prioritization between which hash to use and which file to download.

https://github.com/slaclab/psdm_qs_cli/blob/af994f53ddb9a1b0d4faa093413ddf27d5f77ac5/.travis.yml#L39-L52

This is why builds of https://github.com/pcdshub/happi/pull/118 and https://github.com/pcdshub/happi/pull/121 were previously failing.

**Comment by ZryletTC** [comment]
For now, this issue has been sidestepped by deleting one of the files from Anaconda Cloud.

**Comment by klauer** [comment]
Nice find, @ZryletTC. Would definitely welcome a PR to fix this.

Related: https://github.com/conda-forge/psdm_qs_cli-feedstock psdm_qs_cli and krtc will be on conda-forge shortly, and should help us side-step our local pcds-tag/pcds-dev channels until we can get them sorted.

**Comment by hhslepicka** [comment]
@ZryletTC we use this same recipe of uploading to different channels at multiple projects... it is not duplicated as the if statements are different. One uploads to the TAG channel and another to the DEV.

**Comment by ZryletTC** [comment]
Ahh, @hhslepicka you're right, I didn't catch those three letters change. Then I'm not sure where the duplicate is coming from :neutral_face:

**Comment by klauer** [comment]
* Tokens set to the same value? 
* Upload regardless of matrix settings?

🤷‍♂

**Comment by hhslepicka** [comment]
@klauer:

> Tokens set to the same value?
We will see once something else gets merged in.

> Upload regardless of matrix settings?
if it was the case, we would have the same for tags and that did not happen

**Comment by klauer** [comment]
Will be using the shared CI scripts in #10 - this should be long-since stale after it's merged.
